// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Payload   string      `json:"payload"`
	Result    string      `json:"result"`
	CreatedAt pgtype.Date `json:"created_at"`
}

type User struct {
	ID        int32       `json:"id"`
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	CreatedAt pgtype.Date `json:"created_at"`
}
