# Билдер
FROM golang:1.22 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/main ./cmd/main
COPY --from=builder /app/app.env .
COPY --from=builder /app/internal/repositories/postgresql/migrations internal/repositories/postgresql/migrations/

CMD ["./cmd/main"]